
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: social_app_development
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: localhost

test:
  <<: *default
  database: social_app_test

production:
  primary:
    <<: *default
    database: mysite_production
    username: rails
    host: localhost
    password: <%= ENV["SOCIAL_APP_DATABASE_PASSWORD"] %>